---
- name: Deploy Spring Boot Application
  hosts: seed-hosts
  vars:
    app_name: delivery-schedule-service
    parent_app_name: scheduler-app
    ci_cd_namespace: examples-scheduler-ci-cd
    dev_namespace: examples-scheduler-dev
    test_namespace: examples-scheduler-test
    mongodb:
      DATABASE_SERVICE_NAME: "{{app_name}}-mongodb"
      MONGODB_USER: "{{app_name}}-user"
      MONGODB_PASSWORD: "{{app_name}}-pass"
      MONGODB_DATABASE: "{{app_name}}-db"
    amq:
      APPLICATION_NAME: "{{parent_app_name}}"
      MQ_USERNAME: "{{parent_app_name}}-user"
      MQ_PASSWORD: "{{parent_app_name}}-pass"
    build:
      NAME: "{{app_name}}"
      PIPELINE_SOURCE_REPOSITORY_URL: https://github.com/dwasinge/examples.git
      PIPELINE_SOURCE_REPOSITORY_REF: master
      PIPELINE_CONTEXT_DIR: "scheduler/microservices/{{app_name}}"
      S2I_BASE_IMAGE: redhat-openjdk18-openshift:1.4
    dev:
      NAME: "{{app_name}}"
      PIPELINES_NAMESPACE: "{{ci_cd_namespace}}"
      MONGODB_HOST: "{{ app_name }}-mongodb"
      MONGODB_SECRET: "{{ app_name }}-mongodb"
      MQ_USERNAME: "{{parent_app_name}}-user"
      MQ_PASSWORD: "{{parent_app_name}}-pass"
      MQ_BROKER_URL: "{{ parent_app_name }}-amq-tcp:61616"
    test:
      NAME: "{{app_name}}"
      PIPELINES_NAMESPACE: "{{ci_cd_namespace}}"
      MONGODB_HOST: "{{ app_name }}-mongodb"
      MONGODB_SECRET: "{{ app_name }}-mongodb"
      MQ_USERNAME: "{{parent_app_name}}-user"
      MQ_PASSWORD: "{{parent_app_name}}-pass"
      MQ_BROKER_URL: "{{ parent_app_name }}-amq-tcp:61616"
  tasks:
    - include_role:
        name: openshift-applier/roles/openshift-applier
