---
- name: Deploy Spring Boot Application with MongoDB
  hosts: seed-hosts
  vars:
    app_name: delivery-skills-service
    ci_cd_namespace: examples-scheduler-ci-cd
    dev_namespace: examples-scheduler-dev
    test_namespace: examples-scheduler-test
    postgresqldb:
      DATABASE_SERVICE_NAME: "{{ app_name }}-postgresql"
      POSTGRESQL_USER: "{{app_name}}-user"
      POSTGRESQL_PASSWORD: "{{app_name}}-pass"
      POSTGRESQL_DATABASE: "{{app_name}}-db"
    build:
      NAME: "{{app_name}}"
      PIPELINE_SOURCE_REPOSITORY_URL: https://github.com/dwasinge/examples.git
      PIPELINE_SOURCE_REPOSITORY_REF: master
      PIPELINE_CONTEXT_DIR: "scheduler/microservices/{{app_name}}"
      S2I_BASE_IMAGE: redhat-openjdk18-openshift:1.4
    dev:
      NAME: "{{app_name}}"
      PIPELINES_NAMESPACE: "{{ci_cd_namespace}}"
      POSTGRESQL_URL: "jdbc:postgresql://{{ app_name }}-postgresql:5432/{{ app_name }}-db"
      POSTGRESQL_SECRET: "{{ app_name }}-postgresql"
    test:
      NAME: "{{app_name}}"
      PIPELINES_NAMESPACE: "{{ci_cd_namespace}}"
      POSTGRESQL_URL: "jdbc:postgresql://{{ app_name }}-postgresql:5432/{{ app_name }}-db"
      POSTGRESQL_SECRET: "{{ app_name }}-postgresql"
  tasks:
    - include_role:
        name: openshift-applier/roles/openshift-applier





