---
openshift_cluster_content:
- object: builds
  content:
  - name: "create application build pipeline"
    template: "{{ inventory_dir }}/../templates/binary-template-with-secrets.yml"
    params_from_vars: "{{ build }}"
    namespace: "{{ ci_cd_namespace }}"
    tags:
      - build

